### PR TITLE
Add support for DNS lookups in the reconnection loop

### PR DESCRIPTION
**Pull request by fullylegit**
This change allows hostnames to be provided as the log destination instead of a single IP address.

Each iteration of the reconnection loop will do a DNS lookup if a hostname is provided then attempt to use each result as the destination. 

Existing code that provided a `SocketAddr` as the address will work without modification (like the examples and docs), however code that was using type-inference will need to be updated, eg:

Before 
```rust
Logger::builder().init_tcp("127.0.0.1:12201".parse().unwrap()).unwrap();
```

After
```rust
Logger::builder().init_tcp("127.0.0.1:12201".parse::<SocketAddr>().unwrap()).unwrap();
```

The indentation level of the bg task was starting to look a bit excessive with two more nested loops (for udp, only one for tcp) so I moved what was previously the body of the reconnection loops out into their own functions, however this isn't necessary and can be reverted if you'd prefer.

### CODE REVIEW

**Comment by hlb8122** [comment]
This looks great. I did try have both arguments as `<T: IntoSocketAddr>` to begin with but there was some annoyance with UDP and I gave up and made them both take `SocketAddr` for consistency.

**Comment by hlb8122** [comment]
As this is a breaking change in the way you described, would you be OK with me bumping to tokio 1 before I make a release? I can cut two releases if you'd prefer.

**Comment by fullylegit** [comment]
A single release with tokio 1 will be fine, thanks!

**Comment by hlb8122** [comment]
@fullylegit Should of raised this before I merged. https://github.com/hlb8122/tracing-gelf/pull/8 Thoughts?

**Pull request merged**
