### PR TITLE
Fix logging feedback

### LINKED ISSUE #10: The act of logging produces more logs, causing an infinite loop
It seems that, when trace logs are enabled, the act of sending logs to Graylog itself produces logs. Since those logs will then be sent to Graylog..... we get an infinite loop!

```
2021-06-23T18:38:56.659250405+00:00 TRACE tokio_util::codec::framed_impl: writing; remaining=1002    
2021-06-23T18:38:56.659386680+00:00 TRACE tokio_util::codec::framed_impl: framed transport flushed    
2021-06-23T18:38:56.659539752+00:00 TRACE tokio_util::codec::framed_impl: flushing framed transport    
2021-06-23T18:38:56.659673413+00:00 TRACE tokio_util::codec::framed_impl: writing; remaining=1002    
2021-06-23T18:38:56.659808685+00:00 TRACE tokio_util::codec::framed_impl: framed transport flushed    
2021-06-23T18:38:56.659961482+00:00 TRACE tokio_util::codec::framed_impl: flushing framed transport    
```

I'm currently addressing this by filtering out any logs from `tokio_util`, which is fine for my use case. I'm not sure whether there's a technical solution to this, or if it should just be mentioned in the docs.

### PR DESCRIPTION
**Pull request by hlb8122**
Closes https://github.com/hlb8122/tracing-gelf/issues/10

### CODE REVIEW

**Comment by hlb8122** [comment]
@adeschamps does this fix your problem?

**Comment by adeschamps** [comment]
Yes, I think that solves it nicely.

**Comment by hlb8122** [comment]
@adeschamps Will merge and cut a new version tonight.

@hawkw thanks again for the help

**Comment by hlb8122** [comment]
@adeschamps bumped to 0.5.1 👍

**Pull request merged**
